import { Analytics } from '@vercel/analytics/next'
import { SpeedInsights } from '@vercel/speed-insights/next'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

const clashDisplay = localFont({
  src: [
    {
      path: '../assets/fonts/ClashDisplay/Fonts/OTF/ClashDisplay-Extralight.otf',
      weight: '200',
      style: 'normal',
    },
    {
      path: '../assets/fonts/ClashDisplay/Fonts/OTF/ClashDisplay-Light.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../assets/fonts/ClashDisplay/Fonts/OTF/ClashDisplay-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../assets/fonts/ClashDisplay/Fonts/OTF/ClashDisplay-Medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../assets/fonts/ClashDisplay/Fonts/OTF/ClashDisplay-Semibold.otf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../assets/fonts/ClashDisplay/Fonts/OTF/ClashDisplay-Bold.otf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-clash-display',
  display: 'swap',
})

const spaceGrotesk = localFont({
  src: [
    {
      path: '../assets/fonts/SpaceGrotesk/Fonts/OTF/SpaceGrotesk-Light.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../assets/fonts/SpaceGrotesk/Fonts/OTF/SpaceGrotesk-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../assets/fonts/SpaceGrotesk/Fonts/OTF/SpaceGrotesk-Medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../assets/fonts/SpaceGrotesk/Fonts/OTF/SpaceGrotesk-SemiBold.otf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../assets/fonts/SpaceGrotesk/Fonts/OTF/SpaceGrotesk-Bold.otf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-space-grotesk',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Long Tran Quang',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${clashDisplay.variable} ${spaceGrotesk.variable} antialiased`}>
        {children}
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  )
}
